### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by AlasdairMcKinnon** [leewillis77/dotmailer-api#10]
Hi, 
My dotMailer environment has 4 Child Accounts, so I have 5 API users in total. 

Am I right in thinking that this framework doesn't cater for that at the moment?
I'm happy to develop my own solution but just wanted to check with you first.

Thanks,
Al.

**Comment by leewillis77** [comment]
I'm a bit confused about the question to be honest.

There's nothing to stop you instantiating a copy of the class multiple times each with their own API details, but any given call will only ever use one set of credentials. 

e.g.

```php
<?php

use Dotmailer\Request\AccountRequest;

require('vendor/autoload.php');

$firstConfig = new Dotmailer\Config('config/config1.yml');
$request = new AccountRequest($firstConfig);

$secondConfig = new Dotmailer\Config('config/config2.yml');
$request = new AccountRequest($secondConfig);
```

If I've misunderstood, perhaps you can provide some more detailed information about what you're trying to achieve.

**Comment by AlasdairMcKinnon** [comment]
10 minutes after sending the question I thought that might be the way to go. Thanks for confirming.

Working on a basic script at the moment, but it's working well so far.

Many thanks.

Al.
