### ISSUE TITLE
Bulk Import Functionality

### ISSUE THREAD

**Issue by dharam1987** [leewillis77/dotmailer-api#3]
I am using your code to make API calls to dotmailer, I have found that you have not added code for bulk import of addresses. I have tried the following code and it worked you may consider adding it in your next release.

#FILE - dotmailer-api/src/Dotmailer/Request/AddressbookRequest.php

<pre>
<code>
public function importContacts($book, $filepath) {
        $filename = basename($filepath);
        $filecontents = file_get_contents($filepath);
        $base64encoded = base64_encode($filecontents);
        
        $data = array();
        $data['fileName'] = $filename;
        $data['Data'] = $base64encoded;
        
        $response = $this->request->send(
            'post',
            '/' . $this->findId($book) . '/contacts/import',
            $data
        );                
}
</code>
</pre>
Hope it helps others who are in urgent need.

**Comment by leewillis77** [comment]
Hi; 

You can do bulk imports using the ContactImportRequest class, e.g.

$request = new ContactImportRequest($config);
$request->create($contact_collection);

You'd just need code to map your file to a ContactCollection to pass to the create() method.

**Comment by dharam1987** [comment]
Can you please give an example of how to create the ContactCollection. I
have struggled with it.



Many Thanks
Dharmendra Patri (Dharam)
--
