### ISSUE TITLE
Send Campaign Feature

### ISSUE THREAD

**Issue by stoopkid1** [leewillis77/dotmailer-api#4]
Reading through the source code for the `CampaignRequest()`, I'm unable to tell if there is functionality for Sending a Campaign -- https://developer.dotmailer.com/docs/send-campaign

Does functionality exist within this library for Sending a Campaign?

**Comment by leewillis77** [comment]
Hi; 

Not currently - no - it wasn't needed for the project I built this for. I'd gladly accept a PR though.

**Comment by stoopkid1** [comment]
@leewillis77 thanks for the quick reply -- i wanted to make sure i was reading the source code correctly.

being able to send a campaign is actually the primary objective of the project i'm working on. i'll gladly submit a pull request once i have it work, and any other API calls that may not be supported.

i greatly appreciate the work you've put into this library, so thank you very much
